version: '3'

services:

  web:
    build:
      context: .
      args:
        PURGE_DB: ${PURGE_DB}
        UPDATE_ZONES: ${UPDATE_ZONES}
      dockerfile: Dockerfile
    volumes:
      - static_volume:/code/staticfiles
      - db:/code/db
  
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  graphhopper:
    build: ./graphhopper
    expose:
      - 8989
    volumes:
      - graphhopper_data:/graphhopper_data
    env_file:
    - ./.env

volumes:
  static_volume:
  graphhopper_data:
  db:
  

